spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username:
    password:
logging:
  level:
    com.d: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com.d.mapper/*.xml
  mapper:
    map-key: true